### ISSUE TITLE
Error, while running make

### ISSUE THREAD

**Issue by egordorichev** [hydren/fgeal#1]
When I run `make`, it stops in a few seconds:

> make: *** No rule to make target 'src/futil/string/actions.o', needed by 'libfgeal.so'.  Stop.

Maybe zip package misses some files?
Thanks!

**Comment by hydren** [comment]
Yes, @egordorichev, the zip packages that github automatically make available for download don't include files from a git submodule, which in this case are required for the makefile.

**Comment by hydren** [comment]
I'll make a zip package manually soon. For now, a workaround is to download a zip from the submodule repository (https://github.com/hydren/futil/archive/Rev32.zip) and put the contents inside `/src` folder.

**Comment by hydren** [comment]
Added a release for 0.3.1 tag, containing the missing files. Previous tags need to be built using eclipse, though.

**Comment by egordorichev** [comment]
Hm, but error didn't go away with new build.

**Comment by hydren** [comment]
@egordorichev , I just tested the package and it seems to build. Can you give more details? Is it the same error ("`make: *** No rule to make target 'src/futil/string/actions.o', needed by 'libfgeal.so'. Stop.`")?

What package are you using to build? The one I was talking about is [here](https://github.com/hydren/fgeal/releases/download/0.3.1/fgeal-0.3.1-src.zip).

**Comment by hydren** [comment]
Please note that [this package](https://github.com/hydren/fgeal/archive/0.3.1.zip) provided *automatically* by github still won't build (at least not without the workaround I mentioned in a previous comment).

**Comment by egordorichev** [comment]
Oh, so this [relesase](https://github.com/hydren/fgeal/releases/download/0.3.1/fgeal-0.3.1-src.zip) builds now. But that one from github releases is broken.

**Comment by hydren** [comment]
@egordorichev Exactly. Still trying to figure out a solution. By the way, the "working" build is also on the github release page. Its the *fgeal-0.3.1-src.zip* file, not the *Source code (zip)* or *Source code (tar.gz)* links.
